BASE.DIR=$(PWD)
FX2PROGRAMMER.DIR=$(BASE.DIR)/cycfx2prog-0.47
FX2PROGRAMMER.BIN=$(FX2PROGRAMMER.DIR)/cycfx2prog
PREBUILTS=$(BASE.DIR)/prebuilts
FX2.TI.V17.FIRMWARE.BIN=$(PREBUILTS)/fx2/OPT8241-CDK-FX2-FW_0v17.iic
FIRMWARE.BUILD.DIR=$(BASE.DIR)/build.firmware
FIRMWARE.BIN=$(FIRMWARE.BUILD.DIR)/fx2_main.ihx
BUILD.PREFIX=$(BASE.DIR)/build
BUILD.LIBFTDI=$(BUILD.PREFIX).libftdi
SRC.LIBFTDI=$(BASE.DIR)/libftdi
CMAKE.BIN=cmake
HOST.INSTALLED=$(BASE.DIR)/host.installed
BIN.DIR=$(HOST.INSTALLED)/bin
SRC.EEPROM=$(BASE.DIR)/eeprom
BUILD.EEPROM=$(BUILD.PREFIX).eeprom
EEPROM.BIN=$(BIN.DIR)/eeprom
BUILD.FTDIEEPROM=$(BUILD.PREFIX).ftdi_eeprom
SRC.FTDIEEPROM=$(BASE.DIR)/ftdi_eeprom
SRC.DOCOPT=$(BASE.DIR)/docopt
BUILD.DOCOPT=$(BUILD.PREFIX).docopt
SDCC.INSTALLED=$(HOST.INSTALLED)/sdcc
SRC.SDCC=$(BASE.DIR)/sdcc
SRC.FX2LIB=$(BASE.DIR)/fx2lib
TARGET.INSTALLED=$(BASE.DIR)/target.installed

#bootstrap: sdcc docopt hex2bix fx2lib

docopt: .FORCE
	rm -rf $(BUILD.DOCOPT) && mkdir $(BUILD.DOCOPT) && cd $(BUILD.DOCOPT) && $(CMAKE.BIN) -DCMAKE_INSTALL_PREFIX=$(HOST.INSTALLED) -DCMAKE_BUILT_TYPE=Debug -DCMAKE_INCLUDE_PATH=$(HOST.INSTALLED)/include -DCMAKE_LIBRARY_PATH=$(HOST.INSTALLED)/lib  $(SRC.DOCOPT) && make install

sdcc: .FORCE
	rm -rf $(SDCC.INSTALLED) && cd $(SRC.SDCC)/sdcc && ./configure --prefix=$(SDCC.INSTALLED) && make -j8 install

target.installed: $(TARGET.INSTALLED)/lib
	mkdir $(TARGET.INSTALLED)/lib

fx2lib: .FORCE 	
	cd $(SRC.FX2LIB)/fw && PATH=$(PATH):$(SDCC.INSTALLED)/bin make all && cp $(SRC.FX2LIB)/lib/fx2.lib $(TARGET.INSTALLED)/lib

flash.fx2.ti17: .FORCE
	sudo $(FX2PROGRAMMER.BIN) -id=0451.9105 reset prg:$(FX2.TI.V17.FIRMWARE.BIN) run

flash.fx2.density: .FORCE
	sudo $(FX2PROGRAMMER.BIN) -id=0451.9105 reset prg:$(FIRMWARE.BIN) run

libftdi: .FORCE
	rm -rf $(BUILD.LIBFTDI) && mkdir $(BUILD.LIBFTDI) && cd $(BUILD.LIBFTDI) && $(CMAKE.BIN) $(SRC.LIBFTDI) -DCMAKE_INSTALL_PREFIX=$(HOST.INSTALLED) -DBUILD_TESTS=OFF -DDOCUMENTATION=OFF -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INCLUDE_PATH=$(HOST.INSTALLED)/include -DCMAKE_CROSSCOMPILING=ON -DLIBFTDI_ROOT_DIR=$(HOST.INSTALLED) -DCMAKE_LIBRARY_PATH=$(HOST.INSTALLED)/lib  && make install

eeprom: .FORCE
	rm -rf $(BUILD.EEPROM) && mkdir $(BUILD.EEPROM) && cd $(BUILD.EEPROM) && $(CMAKE.BIN) $(SRC.EEPROM) -DCMAKE_INSTALL_PREFIX=$(HOST.INSTALLED) -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INCLUDE_PATH=$(HOST.INSTALLED)/include && make install


run.eeprom: .FORCE
	$(EEPROM.BIN) --version

ftdi.eeprom: .FORCE
	rm -rf $(BUILD.FTDIEEPROM) && mkdir $(BUILD.FTDIEEPROM) && cd $(BUILD.FTDIEEPROM) && $(CMAKE.BIN) $(SRC.FTDIEEPROM) -DCMAKE_INSTALL_PREFIX=$(HOST.INSTALLED) -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INCLUDE_PATH=$(HOST.INSTALLED)/include && make install


.FORCE:

